> Q. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

mat1 = np.array([[3,6,6],
        [7,5,67],
        [85,35,47]])
mat2 = np.array([[126,76,75],
        [56,85,13],
        [83,94,79]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[ 3  6  6]
 [ 7  5 67]
 [85 35 47]]  and 

[[126  76  75]
 [ 56  85  13]
 [ 83  94  79]]  is 

[[129  82  81]
 [ 63  90  80]
 [168 129 126]] 


> Q. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[3,6,6],
        [7,5,67],
        [85,35,47]])
mat2 = np.array([[126,76,75],
        [56,85,13],
        [83,94,79]])

mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[ 3  6  6]
 [ 7  5 67]
 [85 35 47]]  and 

[[126  76  75]
 [ 56  85  13]
 [ 83  94  79]]  is 

[[ 1212  1302   777]
 [ 6723  7255  5883]
 [16571 13853 10543]] 


> Q. Write a Python Program to Transpose a Matrix?

In [4]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

for i in range(len(X)):
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r) 

[12, 4, 3]
[7, 5, 8]


> Q. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
Arr = input("Enter string : ")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string : i am arup
am
arup
i


> Q. Write a Python Program to Remove Punctuation From a String?

In [15]:
import re
s = "string. With. Punctuation&%#^&$ *%#B*&UT **i#%%t &&^%^&wi*&ll n)(ot sho*&w ?"
s = re.sub(r'[^\w\s]','',s)

print(s)

string With Punctuation BUT it will not show 
